new queue names
ONSdigital/ssdc-rm-caseprocessor pull request #13
Opened 2021-06-23 13:46 UTC by LukeLoze1

# Motivation and Context
Consistent Queue naming

# What has changed
The names of queues 

# How to test?
mvn clean install

# Links
https://trello.com/c/u6RN0Fuo/2372-in-ssdc-fix-queue-names-now-to-be-consistent-5

2021-06-24 16:14 UTC, NickGrantONS commented on README.md
> +queue: events.caseProceessor.surveyLaunched
```suggestion
queue: events.caseProcessor.surveyLaunched
```

2021-06-24 16:15 UTC, NickGrantONS commented on pom.xml
> +              <repository>eu.gcr.io/ssdc-rm-ci/rm/${project.artifactId}</repository>
merge from main and this will disappear

2021-06-24 16:15 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseService.java
> +  public static final String CASE_UPDATE_ROUTING_KEY = "caseProcessor.rh.case";
case what?

2021-06-24 16:15 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ssdc/caseprocessor/service/CaseService.java
> +  public static final String CASE_UPDATE_ROUTING_KEY = "caseProcessor.rh.case";
```suggestion
  public static final String CASE_UPDATE_ROUTING_KEY = "caseProcessor.rh.caseUpdate";
```

2021-06-24 16:15 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ssdc/caseprocessor/service/UacService.java
> +  private static final String UAC_UPDATE_ROUTING_KEY = "caseProcessor.rh.uac";
uac what?

2021-06-24 16:16 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/ssdc/caseprocessor/service/UacService.java
> +  private static final String UAC_UPDATE_ROUTING_KEY = "caseProcessor.rh.uac";
```suggestion
  private static final String UAC_UPDATE_ROUTING_KEY = "caseProcessor.rh.uacUpdate";
```

2021-06-24 16:16 UTC, NickGrantONS commented on src/main/resources/application.yml
> +  print-queue: caseProcessor.printFileSvc.printBatch
```suggestion
  print-queue: caseProcessor.printFileSvc.printBatchRow
```

2021-06-24 16:16 UTC, NickGrantONS commented on src/main/resources/application.yml
> +  refusal-response-queue: events.caseProcessor.refusals
```suggestion
  refusal-response-queue: events.caseProcessor.refusal
```

2021-06-24 16:16 UTC, NickGrantONS commented on src/main/resources/application.yml
> +  receipt-response-queue: events.caseProcessor.responses
```suggestion
  receipt-response-queue: events.caseProcessor.response
```

2021-06-24 16:17 UTC, NickGrantONS commented on src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/TestConstants.java
> +  public static final String OUTBOUND_UAC_QUEUE = "caseProcessor.rh.uac";
```suggestion
  public static final String OUTBOUND_UAC_QUEUE = "caseProcessor.rh.uacUpdate";
```

2021-06-24 16:17 UTC, NickGrantONS commented on src/test/java/uk/gov/ons/ssdc/caseprocessor/testutils/TestConstants.java
> +  public static final String OUTBOUND_CASE_QUEUE = "caseProcessor.rh.case";
```suggestion
  public static final String OUTBOUND_CASE_QUEUE = "caseProcessor.rh.caseUpdate";
```

2021-06-24 16:21 UTC, NickGrantONS requested changes
The only thing that really bothers me is the typo, but.

I would prefer:

- Topic should be more descriptive (i.e. uacUpdate instead of uac)
- Topic should be consistently singular (i.e. addressInvalid instead of responses/invalids/ASDAs/tescos/sainsburysssses)
- This is the last chance to get the standards good and consistent... so let's start as we mean to go on

2021-06-25 13:40 UTC, NickGrantONS commented
update your branch from main please... cant review this as is

2021-06-25 13:41 UTC, NickGrantONS reviewed
Please update from main branch

2021-06-28 13:17 UTC, NickGrantONS approved these changes
Builds and ATs passing 👍

2021-06-28 13:43 UTC, AdamHawtin approved these changes
AT's passing locally 👍

2021-06-28 14:11 UTC, merged