SDCSRM-520 Productionise action rule status
ONSdigital/ssdc-rm-caseprocessor pull request #235
Opened 2024-06-17 12:47 UTC by kacperpONS

# Motivation and Context

Built on #233 

The purpose of this change is to enable us to see more granular detail on what stage of processing each action rule is in. Currently, we only have the has_triggered column and selected case count. These only update once the case selection query has finished. This query can potentially take a long time for very large exercises, and we have no indication at all of when the case processor has finished processing the cases.

The changes here update the new prototype actionRuleStatus field to SELECTING_CASES while the selection query is running, then to PROCESSING_CASES once the selection is complete, then to COMPLETED once there are no cases left to process for the action rule. There is also an ERRORED status used if the rule fails because of bad classifiers, this was previously only indicated in log lines and inferred by the combination of a rule having been triggered but still having a null case count.

# What has changed

- Update actionRuleStatus throughout the action rule lifecycle
- Update tests

# How to test?

Build the linked DDL branch first, then build and run this branch in docker dev

# Links

https://jira.ons.gov.uk/browse/SDCSRM-520

2024-06-17 12:55 UTC, kacperpONS commented
Comment to the above commit: 

If we want the the Action Rule status to update immediately we should utilise a transaction-per-AR  rather than a transaction for all the ARs in the list. 
What's more it should eliminate the overhead of initialising the Transaction when the List is empty.

2024-06-26 13:31 UTC, AdamHawtin requested changes

2024-06-26 13:31 UTC, AdamHawtin commented on pom.xml
> +      <version>4.22.0-SNAPSHOT</version>
TODO: remove `-SNAPSHOT` before merging

2024-07-02 10:48 UTC, dbanks91 approved these changes

2024-07-03 07:36 UTC, AdamHawtin approved these changes

2024-07-03 07:41 UTC, merged